### ISSUE TITLE
自定义的DataTranslator不起作用

### ISSUE THREAD

**Issue by tangbinbinyes** [alibaba/yugong#118]
您好。我要同步的表名是ACD_FILE，我的源表比目标表多了一个"INSERT_TIME"字段，然后我按照AdminGuide自己写了个"ACD_FILEDataTranslator.java"放到了conf/translator文件夹下，可是当我再次运行时，日志还是提示目标表没有INSERT_TIME字段。所以我写的java没有起任何作用

**Comment by gemenhuimofa** [comment]
去掉_试试呢
