### ISSUE TITLE
jar执行报错

### ISSUE THREAD

**Issue by jsnjcrane** [alibaba/yugong#128]
yugong.database.source.username=sa
yugong.database.source.password=123.asddsa
yugong.database.source.type=SqlServer
yugong.database.source.url=jdbc:sqlserver://192.168.2.219:1433;DatabaseName=AdventureWorks
yugong.database.source.encode=UTF-8
yugong.database.source.poolSize=30
yugong.database.target.url=jdbc:mysql://10.81.2.135:3306/test
yugong.database.target.username=test 
yugong.database.target.password=test
yugong.database.target.type=mysql
yugong.database.target.encode=UTF-8
yugong.database.target.poolSize=30
yugong.table.batchApply=true
yugong.table.onceCrawNum=1000
yugong.table.tpsLimit=0
# use connection default schema
yugong.table.ignoreSchema=false
# skip Applier Load Db failed data
yugong.table.skipApplierException=false
#yugong.table.white=yugong_example_join,yugong_example_oracle,yugong_example_two
yugong.table.white=yugong_example_oracle
yugong.table.black=
# tables use multi-thread enable or disable
yugong.table.concurrent.enable=true
# tables use multi-thread size
yugong.table.concurrent.size=5
# retry times 
yugong.table.retry.times=3
# retry interval or sleep time (ms)
yugong.table.retry.interval=1000
# MARK/FULL/INC/ALL(REC+FULL+INC)/CHECK/CLEAR
yugong.table.mode=INC
# yugong extractor
yugong.extractor.dump=false
yugong.extractor.concurrent.enable=true
yugong.extractor.concurrent.global=false
yugong.extractor.concurrent.size=30
yugong.extractor.noupdate.sleep=1000
yugong.extractor.noupdate.thresold=0
yugong.extractor.once=false
# {0} is all columns , {1}.{2} is schemaName.tableName , {3} is primaryKey
#yugong.extractor.sql=select /*+parallel(t)*/ {0} from {1}.{2} t
#yugong.extractor.sql=select * from (select {0} from {1}.{2} t where {3} > ? order by {3} asc) where rownum <= ?
# yugong applier
yugong.applier.concurrent.enable=true
yugong.applier.concurrent.global=false
yugong.applier.concurrent.size=30
yugong.applier.dump=false
# stats
yugong.stat.print.interval=5
yugong.progress.print.interval=1
# alarm email
yugong.alarm.email.host=smtp.163.com
yugong.alarm.email.username=test@163.com
yugong.alarm.email.password=
yugong.alarm.email.stmp.port = 465
yugong.alarm.email.ssl.support=true
yugong.alarm.receiver=test@163.com

**Comment by jsnjcrane** [comment]
2020-03-16 15:43:49.180 [main] INFO  com.taobao.yugong.YugongApp - ## start the YuGong.
2020-03-16 15:43:49.210 [main] ERROR com.taobao.yugong.YugongApp - ## Something goes wrong when starting up the YuGong:
java.lang.IllegalArgumentException: No enum constant com.taobao.yugong.common.model.DbType.SQLSERVER
	at java.lang.Enum.valueOf(Unknown Source)
	at com.taobao.yugong.common.model.DbType.valueOf(DbType.java:6)
	at com.taobao.yugong.controller.YuGongController.init(YuGongController.java:121)
	at com.taobao.yugong.controller.YuGongController.start(YuGongController.java:144)
	at com.taobao.yugong.YugongApp.run(YugongApp.java:67)
	at com.taobao.yugong.YugongApp.main(YugongApp.java:55)

**Comment by jsnjcrane** [comment]
会不会是配置有问题，哪里有配置模板下载

**Comment by jsnjcrane** [comment]
修改配置文件，可以参考其他产线已经在用的配置：
[Files · master · HJArch-Internal / yugong-conf · GitLab](https://gitlab.yeshj.com/hjarch-practice/yugong-conf/tree/master)

**Comment by jsnjcrane** [comment]
这个地址打不开

**Comment by alswl** [comment]
> 修改配置文件，可以参考其他产线已经在用的配置：
> [Files · master · HJArch-Internal / yugong-conf · GitLab](https://gitlab.yeshj.com/hjarch-practice/yugong-conf/tree/master)

这是我的一个 Patch 分支的功能，请参考 [链接失效 · Issue #3 · alswl/yugong](https://github.com/alswl/yugong/issues/3) 这个 Issue。
