### ISSUE TITLE
Oracle实时同步数据到Tidb

### ISSUE THREAD

**Issue by yangrongdeng** [alibaba/yugong#138]
Tidb支持和Mysql相同的协议，使用该工具进行oracle->tidb数据迁移是否有问题

**Comment by alswl** [comment]
可以，另外你也可以看看 [Data Migration](https://docs.pingcap.com/zh/tidb-data-migration/stable/overview)

TiDB 相关更多可以参考 [5 数据迁移方案 · TiDB in Action](https://book.tidb.io/session4/chapter5/data-migration.html)
