### ISSUE TITLE
GetConnectionTimeoutException

### ISSUE THREAD

**Issue by wangfujungit** [alibaba/yugong#23]
DEBUG  流程及数据是这样的 

context.setSourceDs(initDataSource("source"));
	public void setSourceDs(DataSource sourceDs) {

	activeConnections	IdentityHashMap<K,V>  (id=1691)	
		keySet	null
		size	0
		values	null

	{
		CreateTime:"2016-07-22 08:41:44",
		ActiveCount:0,
		PoolingCount:0,
		CreateCount:0,
		DestroyCount:0,
		CloseCount:0,
		ConnectCount:0,
		Connections:[
		]
	}  

context.setTargetDs(initDataSource("target"));	
    activeConnections	IdentityHashMap<K,V>  (id=1794)	
	keySet	null
    modCount	0	
    size	0	
	values	null	
{
	CreateTime:"2016-07-22 08:46:43",
	ActiveCount:0,
	PoolingCount:0,
	CreateCount:0,
	DestroyCount:0,
	CloseCount:0,
	ConnectCount:0,
	Connections:[
	]
}

目的库连接
Connection con = dataSource.getConnection();
得到 ： com.mysql.jdbc.JDBC4Connection@4fe13ac3

源库连接 调用
  whiteTables = TableMetaGenerator.getTableMetasWithoutColumn(globalContext.getSourceDs(),
                            strs[0],
                            strs[1]);
													
  Connection con = dataSource.getConnection();
  抛GetConnectionTimeoutException: wait millis 5000, active 0, maxActive 30

**Comment by wangfujungit** [comment]
但是 我同样用的是  druid-1.0.17.jar，ojdbc14-10.2.0.3.0.jar 驱动及连接包，新建了一个跟YUGONG 毫不相关的 WEB 应用，连接到同一数据库地址，是可以连接上的，但是用YUGONG 就是取不到数据库连接

**Comment by agapple** [comment]
web应用里的超时参数设置的也是一模一样？

2016-08-03 15:27 GMT+08:00 wangfujungit <notifications@github.com>:
