### ISSUE TITLE
迁移数据中文乱码

### ISSUE THREAD

**Issue by xiaohei222** [alibaba/yugong#31]
昨天在试着做oracle to mysql迁移的例子时，发现中文老是乱码。
yugong.properties里两个编码格式，都改过无数次了，可就是乱码。

请问一下，目标和源，应该对应数据库或服务器哪个地方的编码？

**Comment by Qinjiangling** [comment]
遇到过同样问题，应该是mysql数据库编码问题，查看下数据的编码是否都是utf-8。
不方便改数据库编码话，在连接中确定请求的编码格式如：jdbc:mysql://localhost:3306 /mysql?useUnicode=true&characterEncoding=utf-8解决了乱码问题。
大家可以参考下。

**Comment by xiaohei222** [comment]
Qinjiangling
