### ISSUE TITLE
mysql迁入oracle无法实现大字段的写入

### ISSUE THREAD

**Issue by hyper2015** [alibaba/yugong#62]
经过将mysql数据迁入到oracle数据的代码调试和网上翻阅资料 发现
如果是写oracle数据的blob或者clob字段 以下代码无法支撑
for (ColumnValue cv : cvs) {
                            ps.setObject(getIndex(indexs, cv), cv.getValue(), cv.getColumn().getType());
                        }

因为写oracle的clob字段需要指定的对象存在ps无法识别的对象。
--希望分析的结果正确。然后可以帮助到大家

**Comment by agapple** [comment]
你是自己改了代码，源端支持了mysql么？

**Comment by hyper2015** [comment]
是的 我对代码做了微调整后支持了

**Comment by spidersq** [comment]
可以提交到github上么?学习下
