### ISSUE TITLE
关于一些代码片段的讨论

### ISSUE THREAD

**Issue by sanguinar** [alibaba/yugong#63]
最近在做一个类似的项目，看了yugong的代码，感觉写的非常棒！对其中有些部分有些看法想跟你们讨论一下。
1，com.taobao.yugong.applier.IncremectRecordApplier 的getInsertSqlUnit等方法：
        List<String> names = Arrays.asList(record.getSchemaName(), record.getTableName());
        TableSqlUnit sqlUnit = insertSqlCache.get(names);
        if (sqlUnit == null) {
            synchronized (names) {
这里Synchronized一个局部变量，感觉没有意义，我觉得是不是从并发量出发考虑Synchronized（insertSqlCache）或者this，或者去掉Synchronized。
2，com.taobao.yugong.common.db.DataSourceFactory:
     new MapMaker().makeComputingMap已经被废弃并且不能被包外访问了，是不是用
     com.google.common.cache.LoadingCache更合适一些。

**Comment by agapple** [comment]
7e29d66a65c7f05ab4157e972cd2a3c1f2e257e4 ，已经修复问题1

**Comment by agapple** [comment]
MapMaker是以前遗留下来的代码，功能期望就是一个cache
