### ISSUE TITLE
windows bat启动之后一直处于下面的状态，是不是调试代码没有删掉啊

### ISSUE THREAD

**Issue by flayling** [alibaba/yugong#73]
java  -Djava.awt.headless=true -Djava.net.preferIPv4Stack=true -Dapplication.codeset=UTF-8 -Dfile.encoding=UTF-8 -Xms128m -Xmx512m -XX:PermSize=128m -XX:+HeapDumpOnOutOfMemoryError -DappName=yugong -Dlogback.configurationFile="D:\__JYYH\2018\datatool\yugong\bin\\..\conf\logback.xml" -Dyugong.conf="D:\__JYYH\2018\datatool\yugong\bin\\..\conf\yugong.properties"  -server -Xdebug -Xnoagent -Djava.compiler=NONE -Xrunjdwp:transport=dt_socket,address=9099,server=y,suspend=n -classpath "D:\__JYYH\2018\datatool\yugong\bin\\..\conf\..\lib\*;D:\__JYYH\2018\datatool\yugong\bin\\..\conf" com.taobao.yugong.YuGongLauncher
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=128m; support was removed in 8.0
Listening for transport dt_socket at address: 9099

**Comment by agapple** [comment]
这不是报错, windows bat是一个jvm的同步调用, 没有出现ERROR说明正在工作中
