### ISSUE TITLE
hi~请问现在的主分支支持sqlserver<->mysql吗

### ISSUE THREAD

**Issue by maofulin** [alibaba/yugong#82]

**Comment by maofulin** [comment]
@alswl 万分感谢！！！改为jar的方式启动,配置文件跟yugong之前的配置会有什么不同吗,可否提供一个示例呢

**Comment by alswl** [comment]
@maofulin https://github.com/alswl/yugong/tree/feature/sql-server-to-mysql-overview/src/it/resources/sample_config

**Comment by hdpter** [comment]
@alswl 我目前的需求是，将mssql-server 的数据同步到mysql中，但不影响源mssql的数据，也就是说，mssql和mysql数据同时存在，互不影响。yugong是支持的吧？谢谢

**Comment by alswl** [comment]
@hdpter 使用我那个分支是支持的。

**Comment by hdpter** [comment]
@alswl 我已经试用了您开源的yugong，首页感谢您。

**Comment by hdpter** [comment]
@alswl 我已经试用了您开源的yugong，首先感谢您。
我提个疑问：
mssql 如果某一行的数据发生了变化，比如：update 或 delete，如何保证mysql也同样发生了update和delete呢？
我在您发表的mssql cdc文章中，看你描述了cdc。我也开启了cdc，但是您开源的yugong貌似不支持cdc吧。

**Comment by alswl** [comment]
@hdpter 我的分支是支持 CDC 的，这就是增量消费的技术基础。你确认看的是这个 Repo 吧：https://github.com/alswl/yugong

**Comment by alswl** [comment]
@hdpter 这是 CDC 具体消费代码 https://github.com/alswl/yugong/blob/feature/sql-server-to-mysql-overview/src/main/java/com/taobao/yugong/extractor/sqlserver/SqlServerCdcExtractor.java

**Comment by hdpter** [comment]
@alswl 您好，我确认使用的是您的分支。是从您的github上clone的代码，已经实验过，从mssql->mysql是成功的。

**Comment by alswl** [comment]
@hdpter 抱歉，我现在电脑上没有相关的配置，需要周末才能找到数据。

**Comment by hdpter** [comment]
@alswl 谢谢，我根据你给的https://github.com/alswl/yugong/blob/feature/sql-server-to-mysql-overview/src/main/java/com/taobao/yugong/extractor/sqlserver/SqlServerCdcExtractor.java 这个类文件，已经找到了相关配置参数

**Comment by hdpter** [comment]
@alswl 遇到了新问题，合作方的mssql有些表并不在dbo下，而是 tc.record, qx.park等这种方式的表。配置文件yugong.table.white 该如何配置呢？   还是说不支持dbo之外的？

**Comment by yg19861223** [comment]
@alswl 您好，想问下目前分支支持sqlserver->oracle和Oracle->oracle两种么

**Comment by alswl** [comment]
@yg19861223 目前没有支持目标数据库是 Oracle 的功能。

**Comment by yg19861223** [comment]
@alswl 那应该可以自己扩展吧

**Comment by alswl** [comment]
@yg19861223 需要自己写一个 Oracle Writer，全量更新写起来比较容易，增量更新复杂一下，实时同步就再复杂一些。

**Comment by gjhuang** [comment]
> @hdpter 抱歉，我现在电脑上没有相关的配置，需要周末才能找到数据。
> 
> 我看一下，基本改动是
> 
> ```
> yugong.table.mode=INC
> yugong.cdc.time.start=2018-10-30
> yugong.cdc.steptime=600
> ```
不能支持实时的？只能10分钟同步一次？“ CDC扫描器作业”每5分钟向cdc.lsn_time_mapping表添加一个虚拟LSN(事务ID为0x0) 这个5分钟可以修改？大神

**Comment by gjhuang** [comment]
不能支持实时的？只能10分钟同步一次？“ CDC扫描器作业”每5分钟向cdc.lsn_time_mapping表添加一个虚拟LSN(事务ID为0x0) 这个5分钟可以修改？大神
