### ISSUE TITLE
同步主外键的数据，必须保持顺序性？

### ISSUE THREAD

**Issue by jgslvwy** [alibaba/yugong#89]
author,你好,我在做数据迁移的时候发现，如果出现主外键关系的情况下面，迁移会失败,有好的思路解决吗？目前如果想要搞定，是否就得附上依赖关系？@agapple

**Comment by alswl** [comment]
外键依赖关系可以不让迁移工具处理。迁移之前应当去除外键依赖。

**Comment by jgslvwy** [comment]
hello，我们目前oracle同步库之间的迁移是这样做的，但是对于通用性来说，是否有更好的方案，这样可以解决问题，但是对于庞大的财务系统，后台近百张表，我们的工作量也会很大。

**Comment by alswl** [comment]
@jgslvwy 外键依赖本质是有向环形图，很容易产生依赖无法解决的问题。一般只能在业务上解开外键约束。
